export const USER_TYPES = {
    USER_MANAGER : "ADMIN",
    USER_FORMATEUR : "FORMATEUR",
    USER_ETUDIANT : "USER"
}

export const USER_CONNECT = {
    USER_LOGIN : "LOGIN",
    USER_LOGOUT : "LOGOUT"
}